# Generated by Django 5.2.3 on 2025-07-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de estudiante')),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('edad', models.IntegerField(verbose_name='edad de estudiante')),
                ('tipo_estudiante', models.CharField(choices=[('becado', 'Estudiante Becado'), ('no-becado', 'Estudiante No Becado')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Costo de matrícula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasmatriculas', to='administrativo.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=30)),
                ('estudiantes', models.ManyToManyField(through='administrativo.Matricula', to='administrativo.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasmatriculas', to='administrativo.modulo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='modulos',
            field=models.ManyToManyField(through='administrativo.Matricula', to='administrativo.modulo'),
        ),
    ]
